export const state = {
        checkSignedIn: false,
        searchResult: '',
        filterCriteria: '',
        loginFailure: false,
        failureMessage: '',
        signedIn: false,
        keepSignedIn: false,
        user: '',
        signedInStorage: '',
        userCollection: [],
        emailDocumentId: '',
        inCollection: false,
        search: '',
        posterView: false,
        customShelfs: [],
        selectedMovie: [],
        movieNightList: [],
        movieNightButton: false,
        stateFlex: 'row',
        currentDate: new Date(),
        savedMovieNightList: [],
        movieNightListFromDB: [],
        formats: ['Blu-ray', 'DVD', 'Blu-ray/DVD', 'VHS', 'Laserdisc', 'VCD'],
        editions: ["Regular", "Collector's", "Special", "Collection", "Steelbook", "Limited", "Limited/Collection"]
  };